prj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('work.urls')),

]

work/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('predict/', views.predict, name='predict'),
    path('predict/result/', views.result, name='result'),
    path('heart/', views.heart, name='heart'),
    path('heart/run/', views.run, name='run'),
    path('predict/', views.predict, name='predict'),
    path('hospital/', views.hospital, name='hospital'),
    # path('hospital/question_detail', views.question, name='question'),
    path('work/<int:question_id>/', views.question, name='question'),
    path('work/answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('hospital/question_create/', views.question_create, name='question_create'),
]

work/models.py
from django.db import models


class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)

work/forms.py
from django import forms
from work.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성

        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

work/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Question
from django.utils import timezone
from .forms import QuestionForm, AnswerForm
from django.http import HttpResponseNotAllowed


def index(request):
    return render(request, 'work/index.html')

def predict(request):
    return render(request, 'work/predict.html')

def result(request):
    import numpy as np
    import pickle

    sc = pickle.load(open('sc.pkl', 'rb'))
    model = pickle.load(open('diabetes_model.pkl', 'rb'))

    val1 = float(request.GET['n1'])
    val2 = float(request.GET['n2'])
    val3 = float(request.GET['n3'])
    val4 = float(request.GET['n4'])
    val5 = float(request.GET['n5'])
    val6 = float(request.GET['n6'])
    val7 = float(request.GET['n7'])
    val8 = float(request.GET['n8'])

    input_features = np.array([val1, val2, val3, val4, val5, val6, val7, val8])
    pred = model.predict(sc.transform(input_features.reshape(1, -1)))

    result1 = pred
    if pred == [1]:
        result1 = "당뇨병 같은데, 의사선생님께 문의하세요!"
    else:
        result2 = "건강하신거 같은데, 의사선생님께 확인하세요!"

    return render(request, 'work/result.html', {"result_pred":result1})

def heart(request):
    return render(request, 'work/heart.html')

def run(request):
    import numpy as np
    import pickle

    sc = pickle.load(open('heart_sc.pkl', 'rb'))
    model = pickle.load(open('heart_model.pkl', 'rb'))

    val1 = float(request.GET['n1'])
    val2 = float(request.GET['n2'])
    val3 = float(request.GET['n3'])
    val4 = float(request.GET['n4'])
    val5 = float(request.GET['n5'])
    val6 = float(request.GET['n6'])
    val7 = float(request.GET['n7'])
    val8 = float(request.GET['n8'])
    val9 = float(request.GET['n9'])
    val10 = float(request.GET['n10'])
    val11 = float(request.GET['n11'])
    val12 = float(request.GET['n12'])
    val13 = float(request.GET['n13'])

    input_features = np.array([val1, val2, val3, val4, val5, val6, val7, val8, val9, val10, val11, val12, val13])
    re = model.predict(sc.transform(input_features.reshape(1, -1)))

    result1 = re
    if re == [1]:
        result1 = "심장마비 증세가 보이는데, 의사선생님께 문의하세요!"
    else:
        result2 = "심장마비 증세는 보이지 않아요! 그래도 의사선생님께 확인하세요!"

    return render(request, 'work/run.html', {"run_result":result1})

def hospital(request):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    return render(request, 'work/hospital.html', context)


def question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)#Question.objects.get(id=question_id)
    context = {'question': question}
    return render(request, 'work/question_detail.html', context)

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('question', question_id=question.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'question': question, 'form': form}
    return render(request, 'work/question_detail.html', context)

def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('hospital')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'work/question_form.html', context)

work/templates/work/heart.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>건강 예측 웹 서비스</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

        <style>
            body, html {height:100%}
            .bgimg{
                background-image: linear-gradient(rgb(89,208,255),rgb(255,255,255));
                min-height: 100%;
                background-position: center;
                background-size: cover;
            }
            .form-group h1{
                font-size: 50px;
                text-align: center;
                color: rgb(199,20,255);
            }
        </style>
    </head>
    <body>
    <div class="form-group">
        <div class="bgimg">
            <center>
                <div class="form-group">
                    <h1>심장마비 예측을 위해 다음 정보를 입력해주세요.</h1>
                    <p>
                        <form action="run">
                            <input type="text" name="n1" placeholder="나이">
                            <span class="help-block">나이를 입력하세요.</span>

                            <input type="number" name="n2" min="0" max="1" value=0>
                            <span class="help-block">성별을 클릭하세요. (남자는 1, 여자는 0)</span>

                            <input type="number" name="n3" min="0" max="3" value="0">
                            <span class="help-block">가슴 통증 타입 ( 모르면 1입력 )</span>

                            <input type="text" name="n4" placeholder="혈압">
                            <span class="help-block">안정시 혈압을 입력하세요.(휴식하고 있을 때)</span>

                            <input type="text" name="n5" placeholder="혈청 콜레스테롤">
                            <span class="help-block">혈청 콜레스테롤 평균은 100 ~ 129㎎/㎗입니다.</span>

                            <input type="number" name="n6" min="0" max="1" value="0">
                            <span class="help-block">공복 혈당을 입력하세요.(0: 혈당이 120㎎/ℓ 이하, 1: 혈당이 120㎎/ℓ 이상) (정상은 120㎎/ℓ 이하)</span>

                            <input type="number" name="n7" min="0" max="2" value="0">
                            <span class="help-block">심전도 (모르면 1을 입력하세요.)</span>

                            <input type="text" name="n8" placeholder="최대 심장박동 수">
                            <span class="help-block">최대 혈압을 입력하세요.</span>

                            <input type="number" name="n9" min="0" max="1" value="0">
                            <span class="help-block">운동 유도 협심증이 있나요?(no: 0 / yes: 1)</span>

                            <input type="text" name="n10" placeholder="">
                            <span class="help-block">운동에 의해 유발되는 St 우울증을 입력하세요.(평균: 1)</span>

                            <input type="number" name="n11" min="0" max="2" value="0">
                            <span class="help-block">ST 세그먼트의 기울기 (0~2) - (모르면 0을 입력하세요)</span>

                            <input type="number" name="n12" min="0" max="4" value="0">
                            <span class="help-block">혈관의 종류 (0~4) - (모르면 0을 입력하세요.)</span>

                            <input type="number" name="n13" min="0" max="3" value="1">
                            <span class="help-block">빈혈 결과(0: 소적혈구성, 1: 정상, 2 :용혈성, 3: 저색소성 빈혈)</span>
                            <button type="submit">예측하기</button>
                        </form>
                    </p>

                    <br>
                    <p>
                        <form action="{% url 'index' %}">
                            <button type="submit">처음으로 돌아가기</button>
                        </form>
                    </p>
                </div>
            </center>
        </div>
    </div>
    </body>
</html>

work/templates/work/hospital.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>건강 예측 웹 서비스</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <style>
            body, html {height:100%}

            .bgimg{
                background-image: url('https://img.freepik.com/free-vector/people-walking-and-sitting-at-hospital-building-city-clinic-glass-exterior-flat-vector-illustration-for-medical-help-emergency-architecture-healthcare-concept_74855-10130.jpg?w=2000.jpg');
                min-height: 100%;
                background-position: center;
                background-size: cover;
            }
            .sidebar-menu li { width:200px; }

        </style>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="bgimg">
            <center>
                <nav class="navbar navbar-inverse">
                    <div class="container-fluid">
                      <div class="navbar-header">
                        <a class="navbar-brand" href="{% url 'hospital' %}">병원 Top5</a>
                      </div>
                      <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="https://www.amc.seoul.kr/asan/main.do" target='_blank'>서울아산병원</a></li>
                        <li><a href="http://www.samsunghospital.com/home/main/index.do" target='_blank'>삼성서울병원</a></li>
                        <li><a href="http://www.snuh.org/intro.do" target='_blank'>서울대학교병원</a></li>
                        <li><a href="https://sev.severance.healthcare/sev/index.do" target='_blank'>세브란스</a></li>
                        <li><a href="https://www.cmcseoul.or.kr/page/main" target='_blank'>서울성모병원</a></li>
                      </ul>
                    </div>
                </nav>

            </center>
            <div class="container">
                <h1>질의응답</h1>
                <p>답변하고 싶은 질문을 클릭하세요. :)</p>
                <br>
            {% if question_list %}
                <ul class="nav nav-pills nav-stacked">
                {% for question in question_list %}
                    <li class="active"><a href="{% url 'question' question.id %}">{{ question.subject }}</a></li>
                {% endfor %}
                </ul>

            {% else %}
                <p>질문이 없습니다.</p>
            {% endif %}
            <button><a href="{% url 'question_create' %}">질문 등록하기</a></button>
            </div>

        </div>

    </body>
</html>

work/templates/work/index.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>건강 예측 웹 서비스</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <style>
            body, html {
                    height:100%;
                    background: linear-gradient(rgb(89,208,255),rgb(255,255,255));
            }
            *{
                    margin: 0;
                    padding: 0;
                    box-sizing: border-box;
            }

            li{ list-style-type: none;}

            section{
                    height: 440px;
                    padding-top: 38px;
            }

            .box{
                    width: 1020px;
                    margin: 0 auto;
<!--                    border: solid 1px red;-->
            }

            .box h1{
                font-size: 100px;
                text-align: center;
                color: rgb(40,145,255);
            }

            .item{
                    width: 320px;
                    height: 360px;
                    float: left;
                    margin-right: 20px;
                    border:solid 1px #cccccc;
                    margin:auto;
            }

            .item h3{
                    pading: 15px;
                    text-align: center;
            }

            .item p{
                    line-height: 150%;
                    text-align: center;
            }

            .item img{
                    display: block;
                    width: 320px;
                    height: 360px;
            }

            .item form{
                    width:fit-content;
                    margin:auto;
            }
        </style>
    </head>
    <body>

        <section>
            <div class="box">
                <h1>Health Care</h1>
                <div class="item">
                    <img src="https://images.pexels.com/photos/6942171/pexels-photo-6942171.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1">
                    <h3>당뇨병 예측하기!</h3>
                    <p>
                        나의 당뇨병 진단 여부 확인!
                    <form action="predict">
                    <button type="submit">시작하기</button>
                    </form>
                    </p>
                </div>
                <div class="item">
                    <img src="https://images.freeimages.com/variants/KSZEXdmnmfojfiFRRMt8LZbm/f4a36f6589a0e50e702740b15352bc00e4bfaf6f58bd4db850e167794d05993d">
                    <h3>심장마비 예측하기!</h3>
                    <p>
                        나의 심장마비 진단 여부 확인!
                    <form action="heart">
                    <button type="submit">시작하기</button>
                    </form>
                    </p>
                </div>
                <div class="item">
                    <img src="https://images.pexels.com/photos/4386464/pexels-photo-4386464.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1">
                    <h3>병원 찾기!</h3>
                    <p>
                        전국 TOP5 병원
                    <form action="hospital">
                    <button type="submit">병원을 찾아보자~</button>
                    </form>
                    </p>
                </div>
            </div>
        </section>
    </body>
</html>

work/templates/work/predict.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>건강 예측 웹 서비스</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <style>
            body, html {height:100%}
            .bgimg{
                background-image: linear-gradient(rgb(89,208,255),rgb(255,255,255));
                min-height: 100%;
                background-position: center;
                background-size: cover;
            }
            .form-group h1{
                font-size: 50px;
                text-align: center;
                color: rgb(199,20,255);
            }
        </style>
    </head>
    <body>
        <div class="bgimg">
            <center>
                <div class="form-group">
                <h1>당뇨 예측을 위해 다음 정보를 입력해주세요.</h1>
                    <br>
                <p>
                    <form action="result">
                        <input type="text" name="n1" placeholder="임신 횟수">
                        <span class="help-block">임신횟수를 입력하세요.</span>

                        <input type="text" name="n2" placeholder="혈당 수치"><br>
                        <span class="help-block"><a href="https://www.rapportian.com/news/photo/201712/108098_35233_4224.jpg">혈당수치 모르면 클릭</a></span>

                        <input type="text" name="n3" placeholder="혈압(수축기)">
                        <span class="help-block">최대 혈압을 입력하세요.</span>

                        <input type="text" name="n4" placeholder="피부 두께">
                        <span class="help-block">뺨을 엄지손가락과 검지손가락으로 꼬집었을 때 피부 두께를 mm단위로 입력하세요.</span>

                        <input type="text" name="n5" placeholder="인슐린 수치">
                        <span class="help-block">자가혈당 측정기를 사용하세요. (측정기가 없을 시 정상 체중은 공복 인슐린 농도는 약 5-15 uU/mL, 비만인 사람은 15-40 uU/mL)</span>

                        <input type="text" name="n6" placeholder="체질량 지수">
                        <span class="help-block"><a href="https://health.seoulmc.or.kr/healthCareInfo/myBMIPopup.do">체질량 지수 구하기</a></span>

                        <input type="text" name="n7" placeholder="당뇨병 가계력">
                        <span class="help-block">당뇨병 백분율을 입력하세요. (평균: 0.471876)</span>

                        <input type="text" name="n8" placeholder="나이">
                        <span class="help-block">나이를 입력하세요.</span>
                        <br>
                        <button type="submit">예측하기</button>
                    </form>
                </p>

                <br>
                <p>
                    <form action="{% url 'index' %}">
                        <button type="submit">처음으로 돌아가기</button>
                    </form>
                </p>
                </div>
            </center>
        </div>
    </body>
</html>

work/templates/work/question_detail.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>건강 예측 웹 서비스</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <style>
            body, html {height:100%}
            .inco h3{
                border: solid 2px;
            }
            .inco strong{
                color: red;
            }

            .bgimg{
                background-image: url('https://img.freepik.com/free-vector/people-walking-and-sitting-at-hospital-building-city-clinic-glass-exterior-flat-vector-illustration-for-medical-help-emergency-architecture-healthcare-concept_74855-10130.jpg?w=2000.jpg');
                min-height: 100%;
                background-position: center;
                background-size: cover;
            }
            textarea {
                width:100%;
            }
            input[type=submit] {
                margin-top:10px;
            }

            .pu ul{
                width: 300px;
            }

        </style>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>
    <body>


        <div class="bgimg">
            <center>
                <nav class="navbar navbar-inverse">
                    <div class="container-fluid">
                      <div class="navbar-header">
                        <a class="navbar-brand" href="{% url 'hospital' %}">병원 Top5</a>
                      </div>
                      <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="https://www.amc.seoul.kr/asan/main.do" target='_blank'>서울아산병원</a></li>
                        <li><a href="http://www.samsunghospital.com/home/main/index.do" target='_blank'>삼성서울병원</a></li>
                        <li><a href="http://www.snuh.org/intro.do" target='_blank'>서울대학교병원</a></li>
                        <li><a href="https://sev.severance.healthcare/sev/index.do" target='_blank'>세브란스</a></li>
                        <li><a href="https://www.cmcseoul.or.kr/page/main" target='_blank'>서울성모병원</a></li>
                      </ul>
                    </div>
                </nav>

            </center>


            <h1>{{ question.subject }}</h1><br>
            <div class="inco">
                <h3>{{ question.content }}</h3>
            </div>

            <!--수정/삭제-->
<!--            <div class="my-3">-->
<!--                {% if request.user == question.author %}-->
<!--                <a href="{% url 'pybo:question_modify' question.id  %}"-->
<!--                   class="btn btn-sm btn-outline-secondary">수정</a>-->
<!--                {% endif %}-->
<!--            </div>-->

            <!--답변-->
            <h5>{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
            <div class="pu">
                <ul >
                {% for answer in question.answer_set.all %}
                    <li>{{ answer.content }}</li>
                {% endfor %}
                </ul>
            </div>
            <form action="{% url 'answer_create' question.id %}" method="post">
            {% csrf_token %}

            <!-- 오류표시 Start -->
            {% if form.errors %}
            <div class="inco">
                {% for field in form %}
                {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    <strong>{{ field.errors }}</strong>
                </div>
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            <!-- 오류표시 End -->

            <textarea name="content" id="content" rows="15"></textarea>
            <input type="submit" value="답변등록">
            </form>

            <a href="{% url 'hospital' %}"><button>돌아가기</button></a>


        </div>

    </body>
</html>

work/templates/work/question_form.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>건강 예측 웹 서비스</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <style>
            body, html {height:100%}

            .bgimg{
                background-image: url('https://img.freepik.com/free-vector/people-walking-and-sitting-at-hospital-building-city-clinic-glass-exterior-flat-vector-illustration-for-medical-help-emergency-architecture-healthcare-concept_74855-10130.jpg?w=2000.jpg');
                min-height: 100%;
                background-position: center;
                background-size: cover;
            }
            textarea {
                width:100%;
            }
            input[type=submit] {
                margin-top:10px;
            }

        </style>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    </head>
    <body>


        <div class="bgimg">
            <center>
                <nav class="navbar navbar-inverse">
                    <div class="container-fluid">
                      <div class="navbar-header">
                        <a class="navbar-brand" href="{% url 'hospital' %}">병원 Top5</a>
                      </div>
                      <ul class="nav navbar-nav">
                        <li class="active"><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="https://www.amc.seoul.kr/asan/main.do" target='_blank'>서울아산병원</a></li>
                        <li><a href="http://www.samsunghospital.com/home/main/index.do" target='_blank'>삼성서울병원</a></li>
                        <li><a href="http://www.snuh.org/intro.do" target='_blank'>서울대학교병원</a></li>
                        <li><a href="https://sev.severance.healthcare/sev/index.do" target='_blank'>세브란스</a></li>
                        <li><a href="https://www.cmcseoul.or.kr/page/main" target='_blank'>서울성모병원</a></li>
                      </ul>
                    </div>
                </nav>

            </center>
            {% block content %}
            <div class="container">
                <h5>질문등록</h5>
                <form method="post">
                    {% csrf_token %}
                    <!-- 오류표시 Start -->
                    {% if form.errors %}
                    <div>
                        <h2>{% for field in form %}</h2>
                        {% if field.errors %}
                        <div>
                            <strong>{{ field.label }}</strong>
                            {{ field.errors }}
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    {% endif %}
                    <!-- 오류표시 End -->
                    <div>
                        <label for="subject" >제목</label>
                        <input type="text" name="subject" id="subject"
                               value="{{ form.subject.value|default_if_none:'' }}">
                    </div>
                    <div>
                        <label for="content">내용</label>
                        <textarea name="content"
                                  id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
                    </div>
                    <button type="submit">저장하기</button>
                </form>
            </div>
            {% endblock %}
    </body>
</html>

work/templates/work/result.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>건강 예측 웹 서비스</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <style>
            body, html {height:100%}
            .bgimg{
                background-image: linear-gradient(rgb(89,208,255),rgb(255,255,255));
                min-height: 100%;
                background-position: center;
                background-size: cover;
            }

            .bgimg h1{
                color: red;
            }

            .form-group button{
                background-image: linear-gradient(rgb(89,208,255),rgb(255,255,255));
            }
        </style>
    </head>
    <body>
    <div class="container">
        <div class="bgimg">
            <center>
                <div class="form-group">
                    <form action="{% url 'hospital' %}">
                        <button><h1>{{result_pred}}</h1></button>
                        <span class="help-block">문구를 클릭하세요.</span>
                    </form>
                </div>
                <img src="https://cdn.pixabay.com/photo/2018/10/29/21/04/heart-3782056_960_720.png">
                <br>
                <p>
                    <form action="{% url 'index' %}">
                        <button type="submit">처음으로 돌아가기</button>
                    </form>
                </p>

            </center>
        </div>
    </div>
    </body>
</html>

work/templates/work/run.html
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>건강 예측 웹 서비스</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
        <style>
            body, html {height:100%}
            .bgimg{
                background-image: linear-gradient(rgb(89,208,255),rgb(255,255,255));
                min-height: 100%;
                background-position: center;
                background-size: cover;
            }
            .bgimg h1{
                color: red;
            }

            .form-group button{
                background-image: linear-gradient(rgb(89,208,255),rgb(255,255,255));
            }
        </style>
    </head>
    <body>
    <div class="container">
        <div class="bgimg">
            <center>
                <div class="form-group">
                    <form action="{% url 'hospital' %}">
                        <button><h1>{{run_result }}</h1></button>
                        <span class="help-block">문구를 클릭하세요.</span>
                    </form>
                </div>
                <img src="https://cdn.pixabay.com/photo/2013/07/13/09/48/cardiac-156059_960_720.png">
                <br>
                <p>
                    <form action="{% url 'index' %}">
                        <button type="submit">처음으로 돌아가기</button>
                    </form>
                </p>
            </center>
        </div>
    </div>
    </body>
</html>